### ISSUE TITLE
Does not work on Python 2.7 on OS X 10.10.3

### ISSUE THREAD

**Issue by eproxus** [darxtrix/ptop#10]
<img width="2547" alt="screen shot 2015-07-08 at 10 34 18" src="https://cloud.githubusercontent.com/assets/112878/8566241/1f325036-255d-11e5-81b8-d5f8c6971f8b.png">

**Comment by black-perl** [comment]
Hey,

Looks like `psutil` is saying `access_denied`. Check the permissions.

**Comment by eproxus** [comment]
What permissions? Do I have to run this as root?

**Comment by black-perl** [comment]
No, ptop works fine with a normal users as well. OK I got this to help you,

```
You have to run your Python script as root in order to use psutil functions that read information from another process. This is part of the security model on OS X which does not allow one process to read from another process even if they are owned by the same user. Run your script as 'sudo python myscript.py' for example, and you should be able to get CPU information for other processes.
```

here : https://code.google.com/p/psutil/issues/detail?id=254 

Not a ptop issue, I guess.

**Comment by black-perl** [comment]
If you got it working, let me know :smile: , so that I can close this issue.

**Comment by eproxus** [comment]
This is the result of `sudo ptop`:

<img width="2546" alt="screen shot 2015-07-08 at 12 10 59" src="https://cloud.githubusercontent.com/assets/112878/8568023/72639d34-256a-11e5-98f3-780f650f6abb.png">

**Comment by black-perl** [comment]
ok, I got a similar thread to the earlier one pointing OSx to have issues with `psutil` , here https://code.google.com/p/psutil/issues/detail?id=108 .
Sorry, I cannot fix this at the moment as I don't have access to a MAC, I will try to comment a workaround as soon as possible.

Thanks for using it !

**Comment by eproxus** [comment]
Thanks for looking into it.

**Comment by JustusAdam** [comment]
I can report that the same is true for OS X version 10.10.4.

However: If you install the [development version](https://github.com/black-perl/ptop#development) it actually works: 

<img width="969" alt="screen shot 2015-07-08 at 14 37 37" src="https://cloud.githubusercontent.com/assets/5824532/8570167/f1e25a6e-257e-11e5-9963-1f23bac13869.png">

Though only the CPU and MEM view, it does not load the processes list.

**Comment by bede** [comment]
I'm seeing the same bug under Yosemite

**Comment by black-perl** [comment]
@bede , this is a known issue of psutil library with Mac OS. Will explore it more, thanks for reporting !

**Comment by darxtrix** [comment]
The issue with Mac OSX is that `psutil.process_iter()` is returning all the processes that are not owned by the current user. That's why later on the operations such as getting memory percentage, killing the process it giving *Permission Denied*.
```
>>> for proc in psutil.process_iter():
... 	p = psutil.Process(proc.pid)
... 	print proc.pid,proc.username()
...
0 root
1 root
43 root
44 root
46 root
47 root
48 root
```
So, the fix would be to display only the processes onwed by the current user in the Processes table unless the user is privileged enough !
