### ISSUE TITLE
Killing a process making ptop exit abruptly

### ISSUE THREAD

**Issue by darxtrix** [darxtrix/ptop#33]
My guess is that pid of the process is not getting picked up by the kill function properly

<img width="1434" alt="screen shot 2018-03-05 at 9 14 28 pm" src="https://user-images.githubusercontent.com/5263761/36984231-6de5babe-20ba-11e8-9c0c-f94a5a3c2510.png">

**Comment by vinusankarsiitgn** [comment]
Just pass the arguments *args,**kwargs to _kill_process()

**Comment by darxtrix** [comment]
@vinusankarsiitgn are you sure thats gonna help. args and kwargs are not used in the function anywhere. If it was the case it should not be an intermittent issue or they are passed not always i guess ?

**Comment by vinusankars** [comment]
@darxtrix as you rightly said, the kill function does not pass args and kwargs always. But without them you get this issue while killing a process. But with those, I am able to run kill() properly and its working fine. Please see pr #41
