### ISSUE TITLE
After killing terminal misbehaviour

### ISSUE THREAD

**Issue by vinusankars** [darxtrix/ptop#52]
After killing ptop, the terminal displays text "ble, would you like to update (Y/N) ?"
It is not responsive to input and keeps on happening after every kill.
![image](https://user-images.githubusercontent.com/22499917/48860064-e203e580-ede5-11e8-9093-047b9c1055db.png)

**Comment by darxtrix** [comment]
I am not able to reproduce, which version of ptop you are using ? Is it after killing or quitting ?

**Comment by darxtrix** [comment]
@vinusankars Check now if its working properly now, there were some bugs in installation script that i just fixed.

**Comment by vinusankars** [comment]
@darxtrix Great! It is fine now.

**Comment by darxtrix** [comment]
Cool ! thanks for verifying.
