### ISSUE TITLE
When pressing ctrl+c it breaks the terminal

### ISSUE THREAD

**Issue by lunemec** [darxtrix/ptop#6]
ptop closes, but terminal is useless and needs to be restarted.

**Comment by black-perl** [comment]
Yeah, it happens sometime, need to be fixed. Thanks for reporting, use `q` for the time.

**Comment by darxtrix** [comment]
Reproduced issue:

![screen shot 2017-07-12 at 5 53 50 pm](https://user-images.githubusercontent.com/5263761/28117452-1cccd62e-672b-11e7-8c8a-a6047e2460e8.png)

**Comment by vinusankars** [comment]
@darxtrix Have you figured out why this occurs? This never happened with me.

**Comment by darxtrix** [comment]
Yeah it does not occur any more after i have updated the GUI rendering logic. Earlier, the update method for updating the GUI was called in a separate thread job. It seems not to play well with keyboard interactions going on and sometimes it used to break the UI. After that I deferred that responsibility to npyscreen itself and the issue vanished. I think we can close it.

**Comment by vinusankars** [comment]
Alright, we can close the issue.
